[package]
name = "zendb"
version = "1.0.1"
description = "A high-performance document database built for the Internet Computer ecosystem."
keywords = [ "database", "candid", "stable-memory" ]
license = "AGPL-3.0-or-later"
repository = "https://github.com/NatLabs/ZenDB"

[dependencies]
"base@0.16" = "0.16.0"
"core@2.4" = "2.4.0"
"map@9.0" = "9.0.1"
"serde@3.5" = "3.5.0"
"itertools@0.2" = "0.2.2"
"memory-collection@0.4" = "0.4.0"
"bit-map@1.1" = "1.1.0"
"vector@0.4" = "0.4.6"
"augmented-btrees@0.9" = "0.9.0"
"byte-utils@0.2" = "0.2.0"
"lru-cache@2.0" = "2.0.0"
"canister-rbac@0.1" = "0.1.0"

[dev-dependencies]
test = "2.1.2"
bench = "1.0.0"
fuzz = "1.0.0"

[toolchain]
wasmtime = "43.0.0"
moc = "1.4.1"
