name: Makefile CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        name: Build and test
        steps:
            - uses: actions/checkout@v4

            - name: Install dfx
              uses: dfinity/setup-dfx@main
            - name: Confirm successful installation
              run: dfx --version

            - name: Install dfx cache
              run: dfx cache install

            - uses: ZenVoich/setup-mops@v1

            # - name: Detect warnings
            #   run: make check

            - name: Run Tests
              run: mops test
